### ISSUE TITLE
mod launcher crahs on startup - missing locale?

### ISSUE THREAD

**Issue by Arathok** [Mthec/Upkeep-Mod#2]
Hello i am by no means a professional so bear with me. When i try to use the modlauncher it crashes with this line:

`
java.util.MissingResourceException: Can't find bundle for base name mod.wurmonline.mods.upkeepcosts.UpkeepCostsBundle, locale de_DE
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
	at mod.wurmonline.mods.upkeepcosts.UpkeepCosts.<init>(UpkeepCosts.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.gotti.wurmunlimited.modloader.ModInstanceBuilder.createModInstance(ModInstanceBuilder.java:72)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.lambda$loadModsFromModDir$1(ModLoaderShared.java:141)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.loadModsFromModDir(ModLoaderShared.java:143)
	at org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher.main(DelegatedLauncher.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.Loader.run(Loader.java:286)
	at org.gotti.wurmunlimited.serverlauncher.ServerLauncher.main(ServerLauncher.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at PatchedLauncher.main(PatchedLauncher.java:20)

`

i think it has something to do with my language settings. what can i do to fix this? any help would be greatly appreciated

**Comment by Mthec** [comment]
Strange, you are right that message means there is a language issue, however there are no language specific versions in the mod.  It should default to the base file.

I just tried changing the locale on my end and it didn't show an error.

Can I just check you have installed the latest version.  I seem to remember there being an issue with an earlier version.  The start of the logs should say version 1.4.1.

**Comment by Arathok** [comment]
I might be blind, but my server.log doesn't give me any version number, but im happy to provide any other logs! I downloaded the version on the mod thread of the forums.
here is the server.log contents
`[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: ModLoader version v0.40-6fa80d4
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Game version 1.9.1.5
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\announcer\announcer.jar!/META-INF/org.gotti.wurmunlimited.modloader/announcer.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\announcer.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\announcer.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\bagofholding\bagofholding.jar!/META-INF/org.gotti.wurmunlimited.modloader/bagofholding.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\bagofholding.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\bagofholding.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\betterdig.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\betterfarm.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\betterfarm.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\bountymod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\BountyOnBurn.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\BulkOptionsMod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\buyermerchant.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\creatureagemod\creatureagemod.jar!/META-INF/org.gotti.wurmunlimited.modloader/creatureagemod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\creatureagemod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\creatureagemod.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\cropmod\cropmod.jar!/META-INF/org.gotti.wurmunlimited.modloader/cropmod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\cropmod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\cropmod.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\deedmaker.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\DisableFogSpider.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\DiscordRelay.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\Doorbell.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\DUSKombat.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\eventmod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\hitchingpost\hitchingpost.jar!/META-INF/org.gotti.wurmunlimited.modloader/hitchingpost.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\hitchingpost.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\httpserver\httpserver.jar!/META-INF/org.gotti.wurmunlimited.modloader/httpserver.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\httpserver.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\httpserver.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\LeaderboardAndTitles.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\LocationCommand.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\merchantcap.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\moonmetalminingmod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\morecraftables.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\nobuildlimit.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\onetilemining.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\PickMoreSprouts.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\PvpSurfaceMiningSlope.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\riftevent.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\roll.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\sacrificemod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\scriptrunner\scriptrunner.jar!/META-INF/org.gotti.wurmunlimited.modloader/scriptrunner.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\scriptrunner.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\scriptrunner.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\servermap\servermap.jar!/META-INF/org.gotti.wurmunlimited.modloader/servermap.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\servermap.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\servermap.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\serverpacks\serverpacks.jar!/META-INF/org.gotti.wurmunlimited.modloader/serverpacks.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\serverpacks.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\ServerTweaks.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\SinduskLibrary.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\spellmod\spellmod.jar!/META-INF/org.gotti.wurmunlimited.modloader/spellmod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\spellmod.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\spellmod.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\startergear.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\taxidermy.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\TemplarReplacer.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\threedee.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\threedee.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\timerfix.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\TreasureHunting.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\upkeepcosts.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\waxed.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\harvesthelper\harvesthelper.jar!/META-INF/org.gotti.wurmunlimited.modloader/harvesthelper.properties
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModLoaderShared: Reading mods\harvesthelper.config
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\BountyOnBurn\BountyOnBurn.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\BulkOptionsMod\BulkOptionsMod.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\DisableFogSpider\DisableFogSpider.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\DiscordRelay\DiscordRelay.jar, mods\DiscordRelay\libs\JDA-3.3.0_260-withDependencies.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\Doorbell\Doorbell.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\LeaderboardAndTitles\LeaderboardAndTitles.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\LocationCommand\LocationCommand.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\PickMoreSprouts\PickMoreSprouts.jar]
[03:17:08 PM] WARNUNG org.gotti.wurmunlimited.modloader.EarlyLoadingChecker: Mod PickMoreSprouts loaded server class com.wurmonline.ulviirala.mods.PickMoreSprouts during phase load
[03:17:08 PM] WARNUNG org.gotti.wurmunlimited.modloader.EarlyLoadingChecker: Mod PickMoreSprouts loaded server class com.wurmonline.ulviirala.mods.PickMoreSprouts$1 during phase load
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\PvpSurfaceMiningSlope\PvpSurfaceMiningSlope.jar]
[03:17:08 PM] WARNUNG org.gotti.wurmunlimited.modloader.EarlyLoadingChecker: Mod PvpSurfaceMiningSlope loaded server class com.wurmonline.ulviirala.mods.PvpSurfaceMiningSlope during phase load
[03:17:08 PM] WARNUNG org.gotti.wurmunlimited.modloader.EarlyLoadingChecker: Mod PvpSurfaceMiningSlope loaded server class com.wurmonline.ulviirala.mods.PvpSurfaceMiningSlope$1 during phase load
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\SinduskLibrary\SinduskLibrary.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\DUSKombat\DUSKombat.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\ServerTweaks\ServerTweaks.jar, mods\ServerTweaks\libs\commons-codec-1.9.jar, mods\ServerTweaks\libs\poi-3.13-20150929.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\TemplarReplacer\TemplarReplacer.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\TreasureHunting\TreasureHunting.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\announcer\announcer.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\bagofholding\bagofholding.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\betterdig\betterdig.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\betterfarm\betterfarm.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\bountymod\bountymod.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\buyermerchant\buyermerchant.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\creatureagemod\creatureagemod.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\cropmod\cropmod.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\deedmaker\deedmaker.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\eventmod\eventmod.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\hitchingpost\hitchingpost.jar]
[03:17:08 PM] WARNUNG org.gotti.wurmunlimited.modloader.EarlyLoadingChecker: Mod hitchingpost loaded server class com.wurmonline.server.items.ItemTypes during phase load
[03:17:08 PM] WARNUNG org.gotti.wurmunlimited.modloader.EarlyLoadingChecker: Mod hitchingpost loaded server class com.wurmonline.server.MiscConstants during phase load
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\httpserver\httpserver.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\merchantcap\merchantcap.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\moonmetalminingmod\moonmetalminingmod.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\morecraftables\morecraftables.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\nobuildlimit\nobuildlimit.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\onetilemining\onetilemining.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\riftevent\riftevent.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\roll\roll.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\sacrificemod\sacrificemod.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\scriptrunner\scriptrunner.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\serverpacks\serverpacks.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\servermap\servermap.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\spellmod\spellmod.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\startergear\startergear.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\taxidermy\taxidermy.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\threedee\threedee.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\timerfix\timerfix.jar]
[03:17:08 PM] INFORMATION org.gotti.wurmunlimited.modloader.ModInstanceBuilder: Classpath: [mods\upkeepcosts\upkeepcosts.jar]
[03:17:08 PM] SCHWERWIEGEND org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher: Can't find bundle for base name mod.wurmonline.mods.upkeepcosts.UpkeepCostsBundle, locale de_DE
java.util.MissingResourceException: Can't find bundle for base name mod.wurmonline.mods.upkeepcosts.UpkeepCostsBundle, locale de_DE
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
	at mod.wurmonline.mods.upkeepcosts.UpkeepCosts.<init>(UpkeepCosts.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.gotti.wurmunlimited.modloader.ModInstanceBuilder.createModInstance(ModInstanceBuilder.java:72)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.lambda$loadModsFromModDir$1(ModLoaderShared.java:141)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.loadModsFromModDir(ModLoaderShared.java:143)
	at org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher.main(DelegatedLauncher.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.Loader.run(Loader.java:286)
	at org.gotti.wurmunlimited.serverlauncher.ServerLauncher.main(ServerLauncher.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at PatchedLauncher.main(PatchedLauncher.java:20)

`

**Comment by Arathok** [comment]
After a bit of digging i found that my server modlauncher is outdated... so im just plain dumb.
sorry for wasting your time!

**Comment by Mthec** [comment]
No worries, glad you got it sorted.
